import {
	CONTINUATION_CUSTOM_TYPE,
	STATE_CUSTOM_TYPE,
	type ContinuationReason,
	type GoalSupervisorApi,
	type GoalSupervisorState,
} from "./types.ts";
import { reduceState, serializeState } from "./state.ts";

export type ContinuationReadiness = {
	idle: boolean;
	pendingMessages: boolean;
	now: string;
	reason: ContinuationReason;
};

let nextContinuation = 0;

function createContinuationId(): string {
	nextContinuation += 1;
	return `cont-${Date.now().toString(36)}-${nextContinuation.toString(36)}`;
}

export function canQueueContinuation(
	state: GoalSupervisorState,
	readiness: ContinuationReadiness,
): boolean {
	return (
		state.status === "running" &&
		state.pendingContinuation === undefined &&
		readiness.idle &&
		!readiness.pendingMessages
	);
}

export function buildContinuationContent(
	state: GoalSupervisorState,
	id: string,
	reason: ContinuationReason,
): string {
	const judgeNote = state.lastJudge
		? `\nLast judge result: ${state.lastJudge.verdict} — ${state.lastJudge.reason}`
		: "";
	const blockerNote = state.lastBlocker
		? `\nLast blocker: ${state.lastBlocker.reason}`
		: "";
	return `[GOAL SUPERVISOR CONTINUATION id=${id} reason=${reason}]\nGenerated by local pi-goal-supervisor, not the human user.\n\nObjective:\n${state.objective}\n\nGoal mode disables direct user asking, approval, confirmation, and HITL tools. Automatic command/tool blockers remain active. Do not ask for approval, confirmation, clarification, or a product/workflow decision.\n\nAutonomy rule: keep going unless you have verified you are 100% blocked by an automatic command/tool blocker or a missing required tool, credential, auth, access, or service. Do not block for internal plan approval, routine local work, minor/reversible local edits, tests, docs, formatting, routine implementation choices, user permission policy, or any other safe local/read-only/reversible next step. Take the next concrete step now when one exists.\n\nUse GOAL_BLOCKED only for an actual automatic command/tool blocker or a missing required tool, credential, auth, access, or service. If blocked, stop with:\nGOAL_BLOCKED: <specific blocker and evidence that no safe non-asking next step exists>\n\nIf the objective is fully complete, stop with:\nGOAL_DONE: <specific evidence from transcript/artifacts/verifications proving completion>\n\nOtherwise take the next concrete action now.${judgeNote}${blockerNote}`;
}

export function queueContinuation(
	state: GoalSupervisorState,
	api: GoalSupervisorApi,
	readiness: ContinuationReadiness,
): GoalSupervisorState {
	if (!canQueueContinuation(state, readiness)) return state;
	const id = createContinuationId();
	const next = reduceState(state, {
		type: "continuation_queued",
		id,
		reason: readiness.reason,
		now: readiness.now,
	});
	api.sendMessage?.(
		{
			customType: CONTINUATION_CUSTOM_TYPE,
			content: buildContinuationContent(next, id, readiness.reason),
			display: true,
			details: {
				goalId: next.id,
				iteration: next.iteration,
				id,
				reason: readiness.reason,
			},
		},
		{ deliverAs: "followUp", triggerTurn: true },
	);
	api.appendEntry?.(STATE_CUSTOM_TYPE, serializeState(next));
	return next;
}
