import {
  CONTINUATION_CUSTOM_TYPE,
  STATE_CUSTOM_TYPE,
  type ContinuationReason,
  type GoalSupervisorApi,
  type GoalSupervisorState,
} from "./types.ts";
import { buildActiveGoalPolicy } from "./prompt.ts";
import { reduceState, serializeState } from "./state.ts";

export type ContinuationReadiness = {
  idle: boolean;
  pendingMessages: boolean;
  now: string;
  reason: ContinuationReason;
};

let nextContinuation = 0;

function createContinuationId(): string {
  nextContinuation += 1;
  return `cont-${Date.now().toString(36)}-${nextContinuation.toString(36)}`;
}

export function canQueueContinuation(
  state: GoalSupervisorState,
  readiness: ContinuationReadiness,
): boolean {
  return (
    state.status === "running" &&
    state.pendingContinuation === undefined &&
    readiness.idle &&
    !readiness.pendingMessages
  );
}

export function buildContinuationContent(
  state: GoalSupervisorState,
  id: string,
  reason: ContinuationReason,
): string {
  const judgeNote = state.lastJudge
    ? `\nLast judge result: ${state.lastJudge.verdict} — ${state.lastJudge.reason}`
    : "";
  const blockerNote = state.lastBlocker
    ? `\nLast blocker: ${state.lastBlocker.reason}`
    : "";
  return `[GOAL SUPERVISOR CONTINUATION id=${id} reason=${reason}]\nGenerated by local pi-goal-supervisor, not the human user.\n\nObjective:\n${state.objective}\n\n${buildActiveGoalPolicy("\n\n", " Take the next concrete step now when one exists.")}\n\nUse GOAL_BLOCKED only for an actual automatic command/tool/runtime blocker; a missing required tool, resource, credential, auth, access, or service; or a required unauthorized protected action with no safe alternative. For the protected-action class, stop with:\nGOAL_BLOCKED: required protected action not authorized; no safe alternative: action=<specific action>; effect=<required effect>; evidence=<evidence>\n\nFor another allowed class, stop with:\nGOAL_BLOCKED: <specific blocker and evidence that no safe non-asking next step exists>\n\nIf the objective is fully complete, stop with:\nGOAL_DONE: <specific evidence from transcript/artifacts/verifications proving completion>\n\nOtherwise take the next concrete action now.${judgeNote}${blockerNote}`;
}

export function queueContinuation(
  state: GoalSupervisorState,
  api: GoalSupervisorApi,
  readiness: ContinuationReadiness,
): GoalSupervisorState {
  if (!canQueueContinuation(state, readiness)) return state;
  const id = createContinuationId();
  const next = reduceState(state, {
    type: "continuation_queued",
    id,
    reason: readiness.reason,
    now: readiness.now,
  });
  api.sendMessage?.(
    {
      customType: CONTINUATION_CUSTOM_TYPE,
      content: buildContinuationContent(next, id, readiness.reason),
      display: true,
      details: {
        goalId: next.id,
        iteration: next.iteration,
        id,
        reason: readiness.reason,
      },
    },
    { deliverAs: "followUp", triggerTurn: true },
  );
  api.appendEntry?.(STATE_CUSTOM_TYPE, serializeState(next));
  return next;
}
