import {
  CONTINUATION_CUSTOM_TYPE,
  STATE_CUSTOM_TYPE,
  type ContinuationReason,
  type GoalSupervisorApi,
  type GoalSupervisorState,
} from "./types.ts";
import { reduceState, serializeState } from "./state.ts";

export type ContinuationReadiness = {
  idle: boolean;
  pendingMessages: boolean;
  now: string;
  reason: ContinuationReason;
};

let nextContinuation = 0;

function createContinuationId(): string {
  nextContinuation += 1;
  return `cont-${Date.now().toString(36)}-${nextContinuation.toString(36)}`;
}

export function canQueueContinuation(
  state: GoalSupervisorState,
  readiness: ContinuationReadiness,
): boolean {
  return (
    state.status === "running" &&
    state.pendingContinuation === undefined &&
    readiness.idle &&
    !readiness.pendingMessages
  );
}

export function buildContinuationContent(
  state: GoalSupervisorState,
  id: string,
  reason: ContinuationReason,
): string {
  const judgeNote = state.lastJudge
    ? `\nLast judge result: ${state.lastJudge.verdict} — ${state.lastJudge.reason}`
    : "";
  const blockerNote = state.lastBlocker
    ? `\nLast blocker: ${state.lastBlocker.reason}`
    : "";
  return `[GOAL SUPERVISOR CONTINUATION id=${id} reason=${reason}]\nGenerated by local pi-goal-supervisor, not the human user.\n\nObjective:\n${state.objective}\n\nGoal mode uses the normal session configuration, tools, skills, subagents, parent-write ownership, proof, review, reflection, progress, and safety boundaries. It disables direct user asking, approval, confirmation, and HITL tools; automatic command/tool blockers remain active.\n\nDecision-review substitution: whenever a normal session would ask the user an in-scope material product, engineering, or workflow question, do not ask and do not block. Run a substantial review of that exact question with at least three distinct relevant advisors, gather further evidence or review angles as needed, then choose the best supported in-scope answer. Record the selected answer, evidence, assumptions, uncertainty, and rejected alternatives before continuing. Decision review always chooses an answer; it never returns INCONCLUSIVE. Advisors cannot authorize protected actions.\n\nAutonomy rule: keep going unless every safe path is blocked by an automatic command/tool/runtime guardrail, a missing required tool, resource, credential, auth, access, or service, or a required protected action that is not authorized and has no safe alternative. Do not block for product/workflow ambiguity, internal plan approval, routine local work, minor/reversible local edits, tests, docs, formatting, routine implementation choices, or any other safe local/read-only/reversible next step. Take the next concrete step now when one exists.

Contract Gate: for nontrivial implementation, refactor, migration, PR-sized, schema/API, docs-surface, or cross-file goals, build a compact contract card and owner map before editing. The contract card must name the public behavior/API/schema/config/env names, compatibility boundaries, required docs/tests surfaces, explicit non-goals, and forbidden alternate shapes or artifacts. The owner map must identify the likely source-of-truth files/layers that should own the behavior.

Owner map review: during final self-review, explain any expected owner surface that was not touched.

Completion evidence: before GOAL_DONE, map each done criterion to fresh evidence from transcript, artifacts, diffs, checks, docs, or review. Scope and artifact hygiene: account for generated or untracked artifacts, debug outputs, and changed files before completion.

Use GOAL_BLOCKED only for an actual automatic command/tool/runtime blocker; a missing required tool, resource, credential, auth, access, or service; or a required unauthorized protected action with no safe alternative. For the protected-action class, stop with:\nGOAL_BLOCKED: required protected action not authorized; no safe alternative: action=<specific action>; effect=<required effect>; evidence=<evidence>\n\nFor another allowed class, stop with:\nGOAL_BLOCKED: <specific blocker and evidence that no safe non-asking next step exists>\n\nIf the objective is fully complete, stop with:\nGOAL_DONE: <specific evidence from transcript/artifacts/verifications proving completion>\n\nOtherwise take the next concrete action now.${judgeNote}${blockerNote}`;
}

export function queueContinuation(
  state: GoalSupervisorState,
  api: GoalSupervisorApi,
  readiness: ContinuationReadiness,
): GoalSupervisorState {
  if (!canQueueContinuation(state, readiness)) return state;
  const id = createContinuationId();
  const next = reduceState(state, {
    type: "continuation_queued",
    id,
    reason: readiness.reason,
    now: readiness.now,
  });
  api.sendMessage?.(
    {
      customType: CONTINUATION_CUSTOM_TYPE,
      content: buildContinuationContent(next, id, readiness.reason),
      display: true,
      details: {
        goalId: next.id,
        iteration: next.iteration,
        id,
        reason: readiness.reason,
      },
    },
    { deliverAs: "followUp", triggerTurn: true },
  );
  api.appendEntry?.(STATE_CUSTOM_TYPE, serializeState(next));
  return next;
}
